-- Migration 008 : descriptions aromatiques pour tout le catalogue

-- ── FLEURS COMESTIBLES ───────────────────────────────────────────
UPDATE produits SET description = 'Petites fleurs blanches en ombelle au parfum alliacé délicat. Saveur douce de l''ail en finesse, sans l''agressivité du bulbe. Parfaites en finition sur poissons, viandes blanches ou fromages frais.' WHERE reference = '3000';
UPDATE produits SET description = 'Étoiles d''un bleu intense et lumineux, au goût frais et iodé évoquant l''huître et le concombre. L''une des plus spectaculaires sur assiette. Ajouter au dernier moment pour conserver leur couleur.' WHERE reference = '3001';
UPDATE produits SET description = 'Délicat papillon rose et mauve, saveur douce et légèrement sucrée rappelant le pois frais. Très délicate, s''utilise en finition sur des plats raffinés.' WHERE reference = '3002';
UPDATE produits SET description = 'Orange et jaune éclatants, saveur poivrée et moutardée franche. L''une des fleurs les plus goûteuses. Parfaite pour relever salades et carpaccios.' WHERE reference = '3003';
UPDATE produits SET description = 'Pétales orangés en abondance, saveur légèrement amère et épicée avec des notes résineuses. Excellent colorant naturel. S''utilise en pétales séparés pour plus de délicatesse.' WHERE reference = '3004';
UPDATE produits SET description = 'Petites fleurs rose et pourpre à centre jaune, saveur très délicate et légèrement anisée. Pure décoration comestible — pour l''effet visuel avant tout.' WHERE reference = '3005';
UPDATE produits SET description = 'Fleurs orangées de Tagète, saveur citronnée et légèrement épicée. Parfum intense caractéristique. Utiliser les pétales séparés pour une présentation plus raffinée.' WHERE reference = '3006';
UPDATE produits SET description = 'Fleurs aux coloris vifs et variés — orange, rose, rouge, jaune. Saveur neutre à légèrement herbacée. L''atout purement visuel de la collection.' WHERE reference = '3007';
UPDATE produits SET description = 'Fleurs tubulaires rouge vif à l''arôme mentholé et citronné caractéristique. Notes bergamote en finale. Parfait sur desserts, cocktails et viandes rouges.' WHERE reference = '3008';
UPDATE produits SET description = 'Petites ombelles jaune vif au parfum anisé délicat. La signature aromatique de l''aneth en version florale, plus subtile. Idéale sur poissons et carpaccios de légumes.' WHERE reference = '3009';
UPDATE produits SET description = 'Petits pompons bleus au goût discret et légèrement herbacé. La valeur sûre de la décoration florale — couleur bleu unique dans l''assiette.' WHERE reference = '3010';
UPDATE produits SET description = 'Minuscules fleurs blanches en ombelle au parfum herbacé concentré de coriandre. Plus subtile que la feuille. Idéale sur tartares, ceviches et plats asiatiques.' WHERE reference = '3011';
UPDATE produits SET description = 'Fleurs veloutées multicolores aux nuances de violet, jaune et blanc. Saveur neutre légèrement herbacée. L''effet visuel le plus immédiat — décoration d''assiette classique et raffinée.' WHERE reference = '3012';
UPDATE produits SET description = 'Minuscules fleurs blanches en grappes denses, douceur mielleuse et légèrement vanillée. Saveur très délicate. Parfaites en nuage blanc sur des desserts ou des entrées froides.' WHERE reference = '3013';
UPDATE produits SET description = 'Assortiment de fleurs comestibles de saison, sélectionnées pour leur variété visuelle et aromatique. La solution tout-en-un pour apporter couleur et originalité à vos assiettes.' WHERE reference = '3099';

-- ── TAPIS MICRO-POUSSES (produits vivants) ───────────────────────
UPDATE produits SET description = 'Micro-pousses fraîches en plateau vivant — variété selon disponibilité du moment. Saveur concentrée et intense. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0005';
UPDATE produits SET description = 'Saveur piquante, iodée et fraîche caractéristique du cresson. Feuilles rondes d''un vert sombre, tiges croquantes. Compagnon idéal des poissons, des œufs et des viandes blanches. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0006';
UPDATE produits SET description = 'Saveur douce et légèrement terreuse, rappelant les jeunes pousses d''épinard. Tiges et feuilles teintées de rouge-violet remarquable — effet chromatique unique en assiette. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0007';
UPDATE produits SET description = 'Saveur de moutarde délicate et légèrement piquante. Feuilles d''un violet profond aux nervures blanches — l''un des plus spectaculaires visuellement. Idéal pour apporter couleur et caractère aux assiettes. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0008';
UPDATE produits SET description = 'Piquant vif et croquant du radis, légèrement poivré. Tiges rose et pourpre éclatantes surmontées de feuilles vert tendre — contraste visuel remarquable. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '00091';
UPDATE produits SET description = 'Note de moutarde tout en délicatesse, avec un piquant subtil et frais. Feuilles finement dentelées d''un vert vif, qui ressemblent à de minuscules fougères. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0010';
UPDATE produits SET description = 'Piquant franc et net du radis blanc, plus vif que les variétés colorées. Longues tiges blanches et feuilles vert tendre. Parfait sur poissons crus, sushis et plats japonais. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0011';
UPDATE produits SET description = 'Saveur douce et légèrement chou, avec une fraîcheur végétale tendre. Tiges nacrées surmontées de larges feuilles vert profond. Polyvalent et délicat en bouche. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0012';
UPDATE produits SET description = 'Piquant intense et franc, avec une chaleur qui monte progressivement. Feuilles frisées et légèrement gaufrées d''un vert vif. À utiliser avec parcimonie pour un effet maximal. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0013';
UPDATE produits SET description = 'Le piquant poivré et la note de noisette caractéristiques de la roquette, dans une version micro-pousse encore plus concentrée. Feuilles dentelées d''un vert soutenu. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0014';
UPDATE produits SET description = 'Saveur concentrée et légèrement souffrée du brocoli jeune, avec une fraîcheur végétale remarquable. Feuilles rondes d''un vert tendre. Très riche en sulforaphane. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '0015';

-- Colis tapis
UPDATE produits SET description = 'Assortiment de 12 tapis de micro-pousses vivantes, sélectionnés selon la saison et les variétés disponibles. Idéal pour les cuisines à fort volume. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous.' WHERE reference = '0001';
UPDATE produits SET description = 'Assortiment de 16 tapis de micro-pousses vivantes, sélectionnés selon la saison. Notre plus grand format — pour les cuisines exigeantes. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous.' WHERE reference = '0002';
UPDATE produits SET description = 'Assortiment de 6 tapis de micro-pousses vivantes, sélectionnés selon la saison. La formule découverte pour commencer. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous.' WHERE reference = '0004';

-- ── BARQUETTES 10g ───────────────────────────────────────────────
UPDATE produits SET description = 'La signature aromatique intense de la coriandre fraîche dans une version micro-pousse concentrée. Notes herbacées, agrumes et légère touche poivrée. À conserver entre 2 et 4°C, consommer dans les 3 jours.' WHERE reference = '0100';
UPDATE produits SET description = 'Le parfum méditerranéen caractéristique du basilic vert dans une version concentrée et particulièrement tendre. Feuilles charnues d''un vert lumineux. À conserver entre 2 et 4°C.' WHERE reference = '0102';
UPDATE produits SET description = 'Profil aromatique plus complexe que le basilic vert, avec des notes épicées évoquant le clou de girofle. Magnifiques feuilles bordeaux. À conserver entre 2 et 4°C.' WHERE reference = '0103';
UPDATE produits SET description = 'Profil aromatique anisé délicat avec une touche citronnée et herbacée. Feuilles ultrafines et plumeuses d''un vert bleuté. À conserver entre 2 et 4°C.' WHERE reference = '0104';
UPDATE produits SET description = 'Saveur anisée douce et légèrement sucrée évoquant le fenouil bulbe en plus tendre. Feuilles fines et plumeuses d''un vert lumineux. À conserver entre 2 et 4°C.' WHERE reference = '01045';
UPDATE produits SET description = 'Profil aromatique surprenant entre mandarine, fruit de la passion et menthe douce. Feuilles finement découpées d''un vert vif. À conserver entre 2 et 4°C.' WHERE reference = '0105';
UPDATE produits SET description = 'Le profil franc et herbacé du persil dans une version plus concentrée et plus tendre. Petites feuilles découpées d''un vert profond. À conserver entre 2 et 4°C.' WHERE reference = '0106';
UPDATE produits SET description = 'Parfum très reconnaissable des fanes de carotte fraîches, légèrement sucré et herbacé. Feuilles finement découpées d''un vert plumeux. À conserver entre 2 et 4°C.' WHERE reference = '0107';
UPDATE produits SET description = 'Saveur anisée franche et sucrée, plus intense que le fenouil. Feuilles filiformes d''un vert tendre. Idéal avec poissons, fruits de mer et desserts. À conserver entre 2 et 4°C.' WHERE reference = '0108';
UPDATE produits SET description = 'Profil alliacé tout en finesse, plus doux que la ciboulette, avec la signature reconnaissable du poireau jeune. Longues tiges effilées d''un vert tendre. À conserver entre 2 et 4°C.' WHERE reference = '0111';
UPDATE produits SET description = 'L''arôme méditerranéen caractéristique du thym dans une version micro-pousse délicate. Notes camphrées et légèrement citronnées. À conserver entre 2 et 4°C.' WHERE reference = '0112';
UPDATE produits SET description = 'Saveur fraîche et douce, légèrement sucrée. Feuilles caractéristiques en trois lobes d''un vert tendre. Finition délicate sur fromages et charcuteries. À conserver entre 2 et 4°C.' WHERE reference = '0113';
UPDATE produits SET description = 'Saveur végétale douce et tendre, légèrement terreuse. Tiges colorées aux nuances variées (rose, jaune, rouge). À conserver entre 2 et 4°C.' WHERE reference = '0114';
UPDATE produits SET description = 'Saveur douce et légèrement herbacée de l''épinard jeune, sans amertume. Feuilles tendres d''un vert profond. À conserver entre 2 et 4°C.' WHERE reference = '0115';

-- ── BARQUETTES 30g ───────────────────────────────────────────────
UPDATE produits SET description = 'Le piquant poivré et la note de noisette caractéristiques de la roquette, dans une version micro-pousse très concentrée. Feuilles dentelées d''un vert soutenu. À conserver entre 2 et 4°C.' WHERE reference = '0300';
UPDATE produits SET description = 'Piquant intense et franc, avec une chaleur caractéristique de la moutarde jeune. Feuilles légèrement frisées. À utiliser avec parcimonie pour un effet maximal. À conserver entre 2 et 4°C.' WHERE reference = '0301';
UPDATE produits SET description = 'Note de moutarde délicate et piquant subtil. Feuilles finement dentelées comme de minuscules fougères. Idéal pour finitions raffinées. À conserver entre 2 et 4°C.' WHERE reference = '0302';
UPDATE produits SET description = 'Saveur douce et légèrement chou, fraîcheur végétale tendre. Tiges nacrées, feuilles vert profond. Polyvalent en cuisine. À conserver entre 2 et 4°C.' WHERE reference = '0303';
UPDATE produits SET description = 'Piquant vif du radis, tiges rose et pourpre spectaculaires. Finition visuelle et gustative idéale sur poissons et tartares. À conserver entre 2 et 4°C.' WHERE reference = '0304';
UPDATE produits SET description = 'Piquant net et plus vif que les variétés colorées. Longues tiges blanches élancées. Idéal sur poissons crus, sushis et plats japonais. À conserver entre 2 et 4°C.' WHERE reference = '0305';
UPDATE produits SET description = 'Saveur douce et légèrement terreuse. Tiges et feuilles teintées de rouge-violet remarquable — effet chromatique unique en assiette. À conserver entre 2 et 4°C.' WHERE reference = '0306';
UPDATE produits SET description = 'Saveur concentrée du brocoli jeune, légèrement souffrée. Très riche en sulforaphane. Idéal pour les cuisines santé et gastronomiques. À conserver entre 2 et 4°C.' WHERE reference = '0307';
UPDATE produits SET description = 'Piquant iodé et frais caractéristique du cresson. Feuilles rondes d''un vert sombre. Parfait avec poissons, œufs et viandes blanches. À conserver entre 2 et 4°C.' WHERE reference = '0308';

-- ── BARQUETTES 50g / 100g ────────────────────────────────────────
UPDATE produits SET description = 'Mélange de micro-pousses à caractère piquant et aromatique : roquette, moutarde, radis, mizuna. Une sélection affirmée pour ceux qui aiment le caractère et la surprise. À conserver entre 2 et 4°C.' WHERE reference = '0500';
UPDATE produits SET description = 'Mélange de micro-pousses aux saveurs douces et délicates : pois, pak choi, épinard, amarante. Idéal pour tous les palais, y compris les plus sensibles. À conserver entre 2 et 4°C.' WHERE reference = '0500.1';
UPDATE produits SET description = 'Alliance de l''amarante aux reflets pourpres et du brocoli riche en sulforaphane. Saveurs complémentaires, contraste visuel spectaculaire. À conserver entre 2 et 4°C.' WHERE reference = '0501';
UPDATE produits SET description = 'Saveur franchement sucrée évoquant le petit pois frais à peine éclaté, avec un croquant juteux remarquable. Grande barquette pour une utilisation généreuse. À conserver entre 2 et 4°C.' WHERE reference = '0502';
UPDATE produits SET description = 'Saveur franchement sucrée évoquant le petit pois frais à peine éclaté. Tiges tendres surmontées de vrilles fines. Le chouchou des chefs pâtissiers et gastronomiques. À conserver entre 2 et 4°C.' WHERE reference = '0502.1';
UPDATE produits SET description = 'Saveur douce de noisette et légèrement sucrée. Tiges robustes et croquantes surmontées de larges feuilles vert clair. Parfait en salade et en garniture généreuse. À conserver entre 2 et 4°C.' WHERE reference = '0503';
UPDATE produits SET description = 'Sélection de micro-pousses reconnues pour leurs propriétés nutritionnelles : brocoli, radis, cresson. Saveurs variées et profil santé optimal. À conserver entre 2 et 4°C.' WHERE reference = '0504';
UPDATE produits SET description = 'La signature aromatique intense de la coriandre fraîche dans une version micro-pousse très concentrée. Pour les amateurs confirmés et les cuisines spécialisées. À conserver entre 2 et 4°C.' WHERE reference = '0505';
UPDATE produits SET description = 'Bouquet composé de fleurs comestibles Bio de saison, sélectionnées pour leur variété chromatique et aromatique. Parfait pour une présentation remarquable en table ou sur assiette.' WHERE reference = '5000';

-- ── GODETS EXISTANTS (produits vivants) ──────────────────────────
UPDATE produits SET description = 'Assortiment de 6 godets de micro-pousses vivantes en terre, sélectionnés selon la saison. La formule découverte — idéale pour explorer la gamme ou pour un cadeau. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4000';
UPDATE produits SET description = 'Assortiment de 3 godets de micro-pousses vivantes en terre, sélectionnés selon la saison. La formule initiation pour découvrir nos micro-pousses. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4000.1';
UPDATE produits SET description = 'Fleurs étoilées d''un bleu intense au goût frais et iodé évoquant l''huître et le concombre. Feuilles légèrement duveteuses, vert tendre. Une vedette de la décoration comestible. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4018';
UPDATE produits SET description = 'Note acidulée franche avec des nuances ferrugineuses et légèrement métalliques, signature unique de l''oseille sanguine. Feuilles vert sombre veinées de rouge sang. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4051';
UPDATE produits SET description = 'Saveur poivrée et moutardée franche, à la fois piquante et légèrement sucrée. Feuilles rondes d''un vert vif, fleurs orange et jaune comestibles. L''une des micro-pousses les plus généreuses. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4070';
UPDATE produits SET description = 'Parfum citronné délicat et apaisant, avec une légère note mentholée en finale. Petites feuilles ovales d''un vert tendre, légèrement gaufrées. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4071';
UPDATE produits SET description = 'Signature aromatique complexe et unique : notes anisées, citronnées et légèrement camphrées, propre au shiso japonais. Feuilles larges vert foncé aux reflets violacés. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4072';
UPDATE produits SET description = 'Le parfum méditerranéen caractéristique du basilic dans une version micro-pousse concentrée et particulièrement tendre. Feuilles charnues et brillantes d''un vert lumineux. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.' WHERE reference = '4073';

-- ── BOTTES ───────────────────────────────────────────────────────
UPDATE produits SET description = 'Le parfum méditerranéen emblématique en botte fraîche. Notes douces et florales, légèrement poivrées. Cueilli à la main, conditionné en botte pour une utilisation rapide en cuisine.' WHERE reference = '10010';
UPDATE produits SET description = 'Notes épicées intenses évoquant le clou de girofle et les épices orientales. Magnifique feuillage bordeaux aux reflets pourpres — double intérêt aromatique et visuel.' WHERE reference = '10011';
UPDATE produits SET description = 'Arôme anisé délicat avec une touche citronnée et herbacée. Feuilles ultrafines et plumeuses d''un vert bleuté caractéristique. Le compagnon incontournable des poissons et fruits de mer.' WHERE reference = '10012';
UPDATE produits SET description = 'La signature herbacée fraîche et citronnée de la coriandre, l''herbe la plus consommée au monde. Incontournable pour cuisines asiatiques, mexicaines et du Proche-Orient.' WHERE reference = '10013';
UPDATE produits SET description = 'Fraîcheur végétale et légère douceur mentholée, la plus accessible des menthes. Polyvalente en cuisine sucrée et salée, en infusions et en cocktails.' WHERE reference = '10014';
UPDATE produits SET description = 'Fraîcheur mentholée intense et vive, avec une sensation de fraîcheur prolongée en bouche. La menthe aux propriétés digestives les plus marquées — idéale en infusion.' WHERE reference = '10015';
UPDATE produits SET description = 'Parfum floral et citronné évoquant la bergamote, plus élaboré que les menthes classiques. Rare et raffinée, elle surprend et séduit. Magnifique en desserts et cocktails.' WHERE reference = '10016';
UPDATE produits SET description = 'Parfum fruité et sucré étonnant, entre ananas, fruits tropicaux et sauge classique. Une herbe surprise qui intrigue et enchante. Magnifiques fleurs rouges comestibles en saison.' WHERE reference = '10017';
UPDATE produits SET description = 'Saveur alliacée fine et persistante, entre ciboulette et oignon vert jeune. Tiges longues et effilées d''un vert vif. Essentielle dans les cuisines asiatiques.' WHERE reference = '10018';
UPDATE produits SET description = 'Note de moutarde délicate avec un piquant subtil et frais. Feuilles finement dentelées d''un vert vif. La salade japonaise des grands chefs — en botte fraîche pour une utilisation rapide.' WHERE reference = '10019';

-- ── MARAICHAGE / CHAMP ───────────────────────────────────────────
UPDATE produits SET description = 'La courgette ronde traditionnelle de Nice — chair dense, saveur douce et légèrement sucrée, parfaite farcie ou en rondelles. Variété ancienne cultivée Bio selon les méthodes traditionnelles.' WHERE reference = '7000';
UPDATE produits SET description = 'Betteraves fraîches en botte avec leurs fanes, cuites à la vapeur ou rôties pour révéler leur douceur naturelle et leurs notes terreuses profondes. Variété ancienne cultivée sans intrants.' WHERE reference = '7001';
UPDATE produits SET description = 'La courge ronde de Nice, chair ferme et parfumée à la saveur de noisette douce. Se conserve plusieurs semaines. Variété patrimoniale du terroir varois.' WHERE reference = '7002';
UPDATE produits SET description = 'Aubergine à la chair ferme et dense, saveur douce et légèrement fumée à la cuisson. Cultivée Bio en plein soleil varois pour une saveur et une texture maximales.' WHERE reference = '7003';
UPDATE produits SET description = 'Mizuna frais conditionné au kilo pour les restaurants à volume — même fraîcheur et qualité que nos bottes, format professionnel pour une utilisation intensive.' WHERE reference = '10020';
UPDATE produits SET description = 'Laitue rougette à feuilles tendres et légèrement croquantes, saveur douce avec une pointe d''amertume agréable. Cultivée Bio en plein air selon les saisons du Var.' WHERE reference = '11000';
UPDATE produits SET description = 'Batavia croquante à coeur serré, saveur fraîche et légèrement sucrée. La laitue de référence pour les salades composées et les sandwichs en restauration.' WHERE reference = '11001';
