-- Migration 009 : Refonte complete de la nomenclature produits
-- T=Tapis | G=Godets | B=Barquettes | F=Fleurs | H=Herbes/Bottes | C=Champ | L=Livraison

-- Vider le catalogue existant (repart de zero)
TRUNCATE produits CASCADE;

-- ════════════════════════════════════════════════════════════════
-- TAPIS MICRO-POUSSES VIVANTS  T001–T014
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, description, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
('T001', 'Tapis Micropousse',         'Micro-pousses fraîches en plateau vivant — variété selon disponibilité du moment. Saveur concentrée et intense. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                                              'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T002', 'Tapis Cresson',             'Saveur piquante, iodée et fraîche caractéristique du cresson. Feuilles rondes d''un vert sombre, tiges croquantes. Compagnon idéal des poissons, des œufs et des viandes blanches. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                       'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T003', 'Tapis Amarante',            'Saveur douce et légèrement terreuse, rappelant les jeunes pousses d''épinard. Tiges et feuilles teintées de rouge-violet remarquable — effet chromatique unique en assiette. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                             'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T004', 'Tapis Chou rouge',          'Saveur de moutarde délicate et légèrement piquante. Feuilles d''un violet profond aux nervures blanches — l''un des plus spectaculaires visuellement. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                     'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T005', 'Tapis Radis Rose & Pourpre','Piquant vif et croquant du radis, légèrement poivré. Tiges rose et pourpre éclatantes surmontées de feuilles vert tendre — contraste visuel remarquable. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                              'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T006', 'Tapis Mizuna',              'Note de moutarde tout en délicatesse, avec un piquant subtil et frais. Feuilles finement dentelées d''un vert vif, qui ressemblent à de minuscules fougères. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                            'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T007', 'Tapis Radis Daikon',        'Piquant franc et net du radis blanc, plus vif que les variétés colorées. Longues tiges blanches et feuilles vert tendre. Parfait sur poissons crus, sushis et plats japonais. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                          'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T008', 'Tapis Pak choi',            'Saveur douce et légèrement chou, avec une fraîcheur végétale tendre. Tiges nacrées surmontées de larges feuilles vert profond. Polyvalent et délicat en bouche. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                         'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T009', 'Tapis Moutarde',            'Piquant intense et franc, avec une chaleur qui monte progressivement. Feuilles frisées et légèrement gaufrées d''un vert vif. À utiliser avec parcimonie pour un effet maximal. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                          'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T010', 'Tapis Roquette',            'Le piquant poivré et la note de noisette caractéristiques de la roquette, dans une version micro-pousse encore plus concentrée. Feuilles dentelées d''un vert soutenu. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                   'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T011', 'Tapis Brocoli',             'Saveur concentrée et légèrement souffrée du brocoli jeune, avec une fraîcheur végétale remarquable. Très riche en sulforaphane. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                         'TAPIS', 2.00, 5.5, 'tapis', true, true),
('T012', 'Colis mix 6 Tapis',         'Assortiment de 6 tapis de micro-pousses vivantes, sélectionnés selon la saison. La formule découverte pour commencer. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous.',                                                                                                                                              'TAPIS', 12.00, 5.5, 'colis', true, true),
('T013', 'Colis mix 12 Tapis',        'Assortiment de 12 tapis de micro-pousses vivantes, sélectionnés selon la saison et les variétés disponibles. Idéal pour les cuisines à fort volume. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous.',                                                                                                               'TAPIS', 24.00, 5.5, 'colis', true, true),
('T014', 'Colis mix 16 Tapis',        'Assortiment de 16 tapis de micro-pousses vivantes, sélectionnés selon la saison. Notre plus grand format — pour les cuisines exigeantes. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous.',                                                                                                                           'TAPIS', 32.00, 5.5, 'colis', true, true);

-- ════════════════════════════════════════════════════════════════
-- GODETS VIVANTS EN TERRE  G001–G026
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, description, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
('G001', 'Godet Bourrache',       'Fleurs étoilées d''un bleu intense au goût frais et iodé évoquant l''huître et le concombre. Feuilles légèrement duveteuses, vert tendre. Une vedette de la décoration comestible. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                              'GODET', 5.00, 5.5, 'godet', true, true),
('G002', 'Godet Oseille sanguine','Note acidulée franche avec des nuances ferrugineuses et légèrement métalliques, signature unique de l''oseille sanguine. Feuilles vert sombre veinées de rouge sang. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                           'GODET', 5.00, 5.5, 'godet', true, true),
('G003', 'Godet Capucine',        'Saveur poivrée et moutardée franche, à la fois piquante et légèrement sucrée. Feuilles rondes d''un vert vif, fleurs orange et jaune comestibles. L''une des micro-pousses les plus généreuses. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                               'GODET', 5.00, 5.5, 'godet', true, true),
('G004', 'Godet Melisse',         'Parfum citronné délicat et apaisant, avec une légère note mentholée en finale. Petites feuilles ovales d''un vert tendre, légèrement gaufrées. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                 'GODET', 5.00, 5.5, 'godet', true, true),
('G005', 'Godet Shizo',           'Signature aromatique complexe et unique : notes anisées, citronnées et légèrement camphrées, propre au shiso japonais. Feuilles larges vert foncé aux reflets violacés. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                        'GODET', 5.00, 5.5, 'godet', true, true),
('G006', 'Godet Basilic',         'Le parfum méditerranéen caractéristique du basilic dans une version micro-pousse concentrée et particulièrement tendre. Feuilles charnues et brillantes d''un vert lumineux. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                   'GODET', 5.00, 5.5, 'godet', true, true),
('G007', 'Colis mix 3 Godets',    'Assortiment de 3 godets de micro-pousses vivantes en terre, sélectionnés selon la saison. La formule initiation pour découvrir nos micro-pousses. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                              'GODET', 15.00, 5.5, 'colis', true, true),
('G008', 'Colis mix 6 Godets',    'Assortiment de 6 godets de micro-pousses vivantes en terre, sélectionnés selon la saison. La formule découverte — idéale pour explorer la gamme. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                              'GODET', 30.00, 5.5, 'colis', true, true),
('G009', 'Oseille Bio',           'Une saveur franchement acidulée, presque vinaigrée naturellement, qui réveille immédiatement le palais. Petites feuilles tendres en forme de coeur, d''un vert pomme lumineux. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                 'GODET', 5.00, 5.5, 'godet', true, true),
('G010', 'Melisse Bio',           'Parfum citronné délicat et apaisant, avec une légère note mentholée en finale. Petites feuilles ovales d''un vert tendre, légèrement gaufrées. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                 'GODET', 5.00, 5.5, 'godet', true, true),
('G011', 'Coriandre Bio',         'La signature aromatique caractéristique de la coriandre dans une version concentrée : notes herbacées fraîches, agrumes et touche poivrée. Feuilles fines et finement découpées, d''un vert clair. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                            'GODET', 5.00, 5.5, 'godet', true, true),
('G012', 'Pois Bio',              'Saveur franchement sucrée évoquant le petit pois frais à peine éclaté, avec un croquant juteux remarquable. Tiges tendres surmontées de vrilles fines et de larges feuilles d''un vert profond. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                               'GODET', 5.00, 5.5, 'godet', true, true),
('G013', 'Persil Bio',            'Le profil franc et herbacé du persil dans une version plus concentrée et plus tendre. Petites feuilles découpées d''un vert profond, parfum immédiatement reconnaissable. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                      'GODET', 5.00, 5.5, 'godet', true, true),
('G014', 'Agastache Bio',         'Une signature aromatique singulière entre anis, fenouil et réglisse, avec une fraîcheur mentholée en finale. Feuilles allongées et légèrement duveteuses d''un vert grisé. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                     'GODET', 5.00, 5.5, 'godet', true, true),
('G015', 'Mizuna Bio',            'Une note de moutarde tout en délicatesse, avec un piquant subtil et frais. Feuilles finement dentelées d''un vert vif, qui ressemblent à de minuscules fougères. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                              'GODET', 5.00, 5.5, 'godet', true, true),
('G016', 'Cerfeuil Bio',          'Note anisée fine et subtile, herbacée et fraîche, jamais lourde. Feuilles finement ciselées et légèrement ondulées, d''un vert tendre. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                        'GODET', 5.00, 5.5, 'godet', true, true),
('G017', 'Blette Bio',            'Saveur végétale douce et tendre, légèrement terreuse, qui rappelle l''épinard jeune. Tiges colorées (rose, jaune, rouge ou blanche) surmontées de petites feuilles ovales d''un vert profond. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                  'GODET', 5.00, 5.5, 'godet', true, true),
('G018', 'Poireau Bio',           'Un profil alliacé tout en finesse, plus doux que la ciboulette, avec la signature reconnaissable du poireau jeune. Longues tiges effilées d''un vert tendre. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                   'GODET', 5.00, 5.5, 'godet', true, true),
('G019', 'Basilic Vert Bio',      'Le parfum caractéristique du basilic vert dans une version concentrée et particulièrement tendre. Feuilles charnues et brillantes, d''un vert lumineux. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                        'GODET', 5.00, 5.5, 'godet', true, true),
('G020', 'Basilic Pourpre Bio',   'Profil aromatique plus complexe que le basilic vert, avec des notes épicées évoquant le clou de girofle. Magnifiques feuilles bordeaux aux reflets pourpres. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                   'GODET', 5.00, 5.5, 'godet', true, true),
('G021', 'Tagete Patula Bio',     'Profil aromatique surprenant entre mandarine, fruit de la passion et menthe douce. Feuilles finement découpées d''un vert vif délicatement aromatique. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                         'GODET', 5.00, 5.5, 'godet', true, true),
('G022', 'Tagete Lemon Bio',      'Une explosion d''arôme citronné franc et lumineux, plus intense que le citron lui-même. Petites feuilles finement découpées d''un vert tendre. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                 'GODET', 5.00, 5.5, 'godet', true, true),
('G023', 'Trefle Vert Bio',       'Saveur fraîche et douce, légèrement sucrée avec une finale végétale tendre. Feuilles caractéristiques en trois lobes d''un vert tendre. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                        'GODET', 5.00, 5.5, 'godet', true, true),
('G024', 'Carotte Bio',           'Parfum très reconnaissable des fanes de carotte fraîches, légèrement sucré et herbacé. Feuilles finement découpées d''un vert plumeux. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                        'GODET', 5.00, 5.5, 'godet', true, true),
('G025', 'Aneth Bio',             'Profil aromatique anisé délicat avec une touche citronnée et herbacée. Feuilles ultrafines et plumeuses d''un vert bleuté. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                                    'GODET', 5.00, 5.5, 'godet', true, true),
('G026', 'Fenouil Bio',           'Saveur anisée douce et légèrement sucrée évoquant le fenouil bulbe en plus tendre. Feuilles fines et plumeuses d''un vert lumineux. 💧 Produit vivant ! Maintenir le substrat humide en arrosant par dessous. Trempage recommandé 1 à 2 fois par jour.',                                                                                           'GODET', 5.00, 5.5, 'godet', true, true);

-- ════════════════════════════════════════════════════════════════
-- BARQUETTES COUPEES  B001–B032
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, description, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
-- 10g
('B001', 'Barquette 10g Coriandre',        'La signature aromatique intense de la coriandre fraîche dans une version micro-pousse concentrée. Notes herbacées, agrumes et légère touche poivrée. À conserver entre 2 et 4°C, consommer dans les 3 jours.',                                                                             'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B002', 'Barquette 10g Basilic Vert',     'Le parfum méditerranéen caractéristique du basilic vert dans une version concentrée et particulièrement tendre. Feuilles charnues d''un vert lumineux. À conserver entre 2 et 4°C.',                                                                                                       'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B003', 'Barquette 10g Basilic Pourpre',  'Profil aromatique plus complexe que le basilic vert, avec des notes épicées évoquant le clou de girofle. Magnifiques feuilles bordeaux. À conserver entre 2 et 4°C.',                                                                                                                      'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B004', 'Barquette 10g Aneth',            'Profil aromatique anisé délicat avec une touche citronnée et herbacée. Feuilles ultrafines et plumeuses d''un vert bleuté. À conserver entre 2 et 4°C.',                                                                                                                                  'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B005', 'Barquette 10g Fenouil',          'Saveur anisée douce et légèrement sucrée évoquant le fenouil bulbe en plus tendre. Feuilles fines et plumeuses d''un vert lumineux. À conserver entre 2 et 4°C.',                                                                                                                          'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B006', 'Barquette 10g Tagete',           'Profil aromatique surprenant entre mandarine, fruit de la passion et menthe douce. Feuilles finement découpées d''un vert vif. À conserver entre 2 et 4°C.',                                                                                                                               'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B007', 'Barquette 10g Persil',           'Le profil franc et herbacé du persil dans une version plus concentrée et plus tendre. Petites feuilles découpées d''un vert profond. À conserver entre 2 et 4°C.',                                                                                                                         'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B008', 'Barquette 10g Carotte',          'Parfum très reconnaissable des fanes de carotte fraîches, légèrement sucré et herbacé. Feuilles finement découpées d''un vert plumeux. À conserver entre 2 et 4°C.',                                                                                                                       'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B009', 'Barquette 10g Anis',             'Saveur anisée franche et sucrée, plus intense que le fenouil. Feuilles filiformes d''un vert tendre. Idéal avec poissons, fruits de mer et desserts. À conserver entre 2 et 4°C.',                                                                                                         'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B010', 'Barquette 10g Poireau',          'Profil alliacé tout en finesse, plus doux que la ciboulette. Longues tiges effilées d''un vert tendre. À conserver entre 2 et 4°C.',                                                                                                                                                       'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B011', 'Barquette 10g Thym',             'L''arôme méditerranéen caractéristique du thym dans une version micro-pousse délicate. Notes camphrées et légèrement citronnées. À conserver entre 2 et 4°C.',                                                                                                                             'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B012', 'Barquette 10g Trefle',           'Saveur fraîche et douce, légèrement sucrée. Feuilles en trois lobes d''un vert tendre. Finition délicate sur fromages et charcuteries. À conserver entre 2 et 4°C.',                                                                                                                       'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B013', 'Barquette 10g Blette',           'Saveur végétale douce et tendre, légèrement terreuse. Tiges colorées aux nuances variées (rose, jaune, rouge). À conserver entre 2 et 4°C.',                                                                                                                                               'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B014', 'Barquette 10g Epinard',          'Saveur douce et légèrement herbacée de l''épinard jeune, sans amertume. Feuilles tendres d''un vert profond. À conserver entre 2 et 4°C.',                                                                                                                                                 'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
-- 30g
('B015', 'Barquette 30g Roquette',         'Le piquant poivré et la note de noisette de la roquette en version micro-pousse très concentrée. Feuilles dentelées d''un vert soutenu. À conserver entre 2 et 4°C.',                                                                                                                      'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B016', 'Barquette 30g Moutarde',         'Piquant intense et franc, avec une chaleur caractéristique de la moutarde jeune. Feuilles légèrement frisées. À utiliser avec parcimonie. À conserver entre 2 et 4°C.',                                                                                                                    'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B017', 'Barquette 30g Mizuna',           'Note de moutarde délicate et piquant subtil. Feuilles finement dentelées comme de minuscules fougères. À conserver entre 2 et 4°C.',                                                                                                                                                       'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B018', 'Barquette 30g Pak choi',         'Saveur douce et légèrement chou, fraîcheur végétale tendre. Tiges nacrées, feuilles vert profond. À conserver entre 2 et 4°C.',                                                                                                                                                            'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B019', 'Barquette 30g Radis R/P',        'Piquant vif du radis, tiges rose et pourpre spectaculaires. Finition visuelle et gustative idéale sur poissons et tartares. À conserver entre 2 et 4°C.',                                                                                                                                  'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B020', 'Barquette 30g Radis Daikon',     'Piquant net du radis blanc, plus vif. Longues tiges blanches élancées. Idéal sur poissons crus et plats japonais. À conserver entre 2 et 4°C.',                                                                                                                                            'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B021', 'Barquette 30g Amarante',         'Saveur douce et légèrement terreuse. Tiges et feuilles teintées de rouge-violet remarquable. À conserver entre 2 et 4°C.',                                                                                                                                                                 'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B022', 'Barquette 30g Brocoli',          'Saveur concentrée du brocoli jeune. Très riche en sulforaphane. Idéal pour les cuisines santé et gastronomiques. À conserver entre 2 et 4°C.',                                                                                                                                             'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B023', 'Barquette 30g Cresson',          'Piquant iodé et frais du cresson. Feuilles rondes d''un vert sombre. Parfait avec poissons, œufs et viandes blanches. À conserver entre 2 et 4°C.',                                                                                                                                        'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
-- 50g+
('B024', 'Barquette 50g Mix epice',        'Mélange de micro-pousses piquantes et aromatiques : roquette, moutarde, radis, mizuna. Pour ceux qui aiment le caractère. À conserver entre 2 et 4°C.',                                                                                                                                    'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B025', 'Barquette 50g Mix doux',         'Mélange de micro-pousses aux saveurs douces : pois, pak choi, épinard, amarante. Idéal pour tous les palais. À conserver entre 2 et 4°C.',                                                                                                                                                 'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B026', 'Barquette 50g Amarante/Brocoli', 'Alliance de l''amarante aux reflets pourpres et du brocoli riche en sulforaphane. Saveurs complémentaires, contraste visuel spectaculaire. À conserver entre 2 et 4°C.',                                                                                                                   'BARQUETTE', 10.00, 5.5, 'barquette', true, true),
('B027', 'Barquette 100g Petit pois',      'Saveur franchement sucrée évoquant le petit pois frais à peine éclaté, croquant juteux remarquable. Grande barquette pour une utilisation généreuse. À conserver entre 2 et 4°C.',                                                                                                          'BARQUETTE', 10.00, 5.5, 'barquette', false, true),
('B028', 'Barquette 50g Petit pois',       'Saveur franchement sucrée évoquant le petit pois frais. Tiges tendres surmontées de vrilles fines. Le chouchou des chefs gastronomiques. À conserver entre 2 et 4°C.',                                                                                                                     'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B029', 'Barquette 50g Tournesol',        'Saveur douce de noisette et légèrement sucrée. Tiges robustes et croquantes, larges feuilles vert clair. Parfait en garniture généreuse. À conserver entre 2 et 4°C.',                                                                                                                     'BARQUETTE', 5.00, 5.5, 'barquette', false, true),
('B030', 'Barquette 50g Melange vitalite', 'Sélection de micro-pousses aux propriétés nutritionnelles : brocoli, radis, cresson. Profil santé optimal. À conserver entre 2 et 4°C.',                                                                                                                                                   'BARQUETTE', 5.00, 5.5, 'barquette', true, true),
('B031', 'Barquette 50g Coriandre',        'La signature aromatique intense de la coriandre en version micro-pousse très concentrée. Pour les cuisines spécialisées. À conserver entre 2 et 4°C.',                                                                                                                                     'BARQUETTE', 25.00, 5.5, 'barquette', false, true),
('B032', 'Bouquet de fleurs',              'Bouquet de fleurs comestibles Bio de saison, sélectionnées pour leur variété chromatique et aromatique. Parfait pour une présentation remarquable en table ou sur assiette.',                                                                                                                'BARQUETTE', 5.00, 5.5, 'bouquet', true, true);

-- ════════════════════════════════════════════════════════════════
-- FLEURS COMESTIBLES  F001–F015
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, description, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
('F001', 'Fleurs Ail',           'Petites fleurs blanches en ombelle au parfum alliacé délicat. Saveur douce de l''ail en finesse, sans l''agressivité du bulbe. Parfaites en finition sur poissons, viandes blanches ou fromages frais.',                                 'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F002', 'Fleurs Bourrache',     'Étoiles d''un bleu intense et lumineux, au goût frais et iodé évoquant l''huître et le concombre. L''une des plus spectaculaires sur assiette. Ajouter au dernier moment pour conserver leur couleur.',                                  'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F003', 'Fleurs Petit pois',    'Délicat papillon rose et mauve, saveur douce et légèrement sucrée rappelant le pois frais. Très délicate, s''utilise en finition sur des plats raffinés.',                                                                               'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F004', 'Fleurs Capucine',      'Orange et jaune éclatants, saveur poivrée et moutardée franche. L''une des fleurs les plus goûteuses. Parfaite pour relever salades et carpaccios.',                                                                                     'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F005', 'Fleurs Calendula',     'Pétales orangés en abondance, saveur légèrement amère et épicée avec des notes résineuses. Excellent colorant naturel. S''utilise en pétales séparés pour plus de délicatesse.',                                                         'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F006', 'Fleurs Cosmos',        'Petites fleurs rose et pourpre à centre jaune, saveur très délicate et légèrement anisée. Pure décoration comestible — pour l''effet visuel avant tout.',                                                                                 'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F007', 'Fleurs Oeillet Inde',  'Fleurs orangées de Tagète, saveur citronnée et légèrement épicée. Parfum intense caractéristique. Utiliser les pétales séparés pour une présentation plus raffinée.',                                                                    'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F008', 'Fleurs Zinnia',        'Fleurs aux coloris vifs et variés — orange, rose, rouge, jaune. Saveur neutre à légèrement herbacée. L''atout purement visuel de la collection.',                                                                                         'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F009', 'Fleurs Monarde',       'Fleurs tubulaires rouge vif à l''arôme mentholé et citronné caractéristique. Notes bergamote en finale. Parfait sur desserts, cocktails et viandes rouges.',                                                                              'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F010', 'Fleurs Aneth',         'Petites ombelles jaune vif au parfum anisé délicat. La signature aromatique de l''aneth en version florale, plus subtile. Idéale sur poissons et carpaccios de légumes.',                                                                 'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F011', 'Fleurs Bleuet',        'Petits pompons bleus au goût discret et légèrement herbacé. La valeur sûre de la décoration florale — couleur bleu unique dans l''assiette.',                                                                                             'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F012', 'Fleurs Coriandre',     'Minuscules fleurs blanches en ombelle au parfum herbacé concentré de coriandre. Plus subtile que la feuille. Idéale sur tartares, ceviches et plats asiatiques.',                                                                        'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F013', 'Fleurs Pensee',        'Fleurs veloutées multicolores aux nuances de violet, jaune et blanc. Saveur neutre légèrement herbacée. L''effet visuel le plus immédiat — décoration d''assiette classique et raffinée.',                                                'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F014', 'Fleurs Alysse',        'Minuscules fleurs blanches en grappes denses, douceur mielleuse et légèrement vanillée. Saveur très délicate. Parfaites en nuage blanc sur des desserts ou des entrées froides.',                                                         'FLEUR', 6.00, 5.5, 'barquette', true, true),
('F015', 'Fleurs MIX',           'Assortiment de fleurs comestibles de saison, sélectionnées pour leur variété visuelle et aromatique. La solution tout-en-un pour apporter couleur et originalité à vos assiettes.',                                                       'FLEUR', 6.00, 5.5, 'barquette', true, true);

-- ════════════════════════════════════════════════════════════════
-- HERBES & BOTTES  H001–H011
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, description, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
('H001', 'Botte Basilic Vert',      'Le parfum méditerranéen emblématique en botte fraîche. Notes douces et florales, légèrement poivrées. Cueilli à la main pour une utilisation rapide en cuisine.',                                                                    'BOTTE', 2.00, 5.5, 'botte', false, true),
('H002', 'Botte Basilic Pourpre',   'Notes épicées intenses évoquant le clou de girofle et les épices orientales. Magnifique feuillage bordeaux aux reflets pourpres — double intérêt aromatique et visuel.',                                                             'BOTTE', 2.00, 5.5, 'botte', false, true),
('H003', 'Botte Aneth',             'Arôme anisé délicat avec une touche citronnée et herbacée. Feuilles ultrafines et plumeuses d''un vert bleuté. Le compagnon incontournable des poissons et fruits de mer.',                                                          'BOTTE', 2.00, 5.5, 'botte', false, true),
('H004', 'Botte Coriandre',         'La signature herbacée fraîche et citronnée de la coriandre. Incontournable pour cuisines asiatiques, mexicaines et du Proche-Orient.',                                                                                                'BOTTE', 2.00, 5.5, 'botte', false, true),
('H005', 'Botte Menthe verte',      'Fraîcheur végétale et légère douceur mentholée, la plus accessible des menthes. Polyvalente en cuisine sucrée et salée, en infusions et cocktails.',                                                                                  'BOTTE', 1.50, 5.5, 'botte', true, true),
('H006', 'Botte Menthe poivree',    'Fraîcheur mentholée intense et vive, sensation prolongée en bouche. La menthe aux propriétés digestives les plus marquées — idéale en infusion.',                                                                                     'BOTTE', 1.50, 5.5, 'botte', true, true),
('H007', 'Botte Menthe Bergamotte', 'Parfum floral et citronné évoquant la bergamote, plus élaboré que les menthes classiques. Rare et raffinée, elle surprend et séduit en desserts et cocktails.',                                                                       'BOTTE', 1.50, 5.5, 'botte', true, true),
('H008', 'Botte Sauge Ananas',      'Parfum fruité et sucré étonnant entre ananas, fruits tropicaux et sauge. Une herbe surprise qui intrigue et enchante. Fleurs rouges comestibles en saison.',                                                                          'BOTTE', 2.00, 5.5, 'botte', true, true),
('H009', 'Botte Ciboule de Chine',  'Saveur alliacée fine et persistante, entre ciboulette et oignon vert. Tiges longues et effilées d''un vert vif. Essentielle dans les cuisines asiatiques.',                                                                          'BOTTE', 1.50, 5.5, 'botte', true, true),
('H010', 'Botte Mizuna',            'Note de moutarde délicate avec un piquant subtil. Feuilles finement dentelées d''un vert vif. La salade japonaise des grands chefs, en botte fraîche.',                                                                               'BOTTE', 1.50, 5.5, 'botte', true, true),
('H011', 'Mizuna au kilo',          'Mizuna frais conditionné au kilo pour les restaurants à volume. Même fraîcheur et qualité que nos bottes, format professionnel.',                                                                                                     'CHAMP', 9.00, 5.5, 'kg', true, true);

-- ════════════════════════════════════════════════════════════════
-- CHAMP / MARAICHAGE  C001–C006
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, description, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
('C001', 'Courgette de Nice',   'La courgette ronde traditionnelle de Nice — chair dense, saveur douce et légèrement sucrée. Parfaite farcie ou en rondelles. Variété ancienne cultivée Bio.',                                                                          'CHAMP', 4.00, 5.5, 'unite', true, true),
('C002', 'Betteraves botte',    'Betteraves fraîches en botte avec leurs fanes. Cuites à la vapeur ou rôties, douceur naturelle et notes terreuses profondes. Variété ancienne cultivée sans intrants.',                                                                 'CHAMP', 2.00, 5.5, 'botte', true, true),
('C003', 'Courge de Nice',      'La courge ronde de Nice, chair ferme à la saveur de noisette douce. Se conserve plusieurs semaines. Variété patrimoniale du terroir varois.',                                                                                           'CHAMP', 2.50, 5.5, 'unite', true, true),
('C004', 'Aubergine',           'Aubergine à la chair ferme et dense, saveur douce et légèrement fumée à la cuisson. Cultivée Bio en plein soleil varois.',                                                                                                              'CHAMP', 5.50, 5.5, 'unite', true, true),
('C005', 'Rougette',            'Laitue rougette à feuilles tendres et légèrement croquantes, saveur douce avec une pointe d''amertume agréable. Cultivée Bio en plein air dans le Var.',                                                                                'CHAMP', 1.20, 5.5, 'unite', true, true),
('C006', 'Batavia',             'Batavia croquante à coeur serré, saveur fraîche et légèrement sucrée. La laitue de référence pour les salades composées en restauration.',                                                                                              'CHAMP', 1.20, 5.5, 'unite', true, true);

-- ════════════════════════════════════════════════════════════════
-- LIVRAISON  L001–L003
-- ════════════════════════════════════════════════════════════════
INSERT INTO produits (reference, designation, categorie, prix_ht, tva_pct, unite, bio, actif) VALUES
('L001', 'Livraison', 'LIVRAISON', 2.00, 5.5, 'forfait', false, true),
('L002', 'Livraison', 'LIVRAISON', 3.00, 5.5, 'forfait', false, true),
('L003', 'Livraison', 'LIVRAISON', 5.00, 5.5, 'forfait', false, true);
